// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/common/qiniu_token": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取七牛云token",
                "responses": {
                    "200": {
                        "description": "ok\" \"七牛云token",
                        "schema": {
                            "$ref": "#/definitions/entity.GetBucketTokenResp"
                        }
                    }
                }
            }
        },
        "/common/r2_signed_url": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取Cloudflare R2预上传链接",
                "responses": {
                    "200": {
                        "description": "ok\" \"Cloudflare R2预上传链接",
                        "schema": {
                            "$ref": "#/definitions/entity.GetSignedURLResp"
                        }
                    }
                }
            }
        },
        "/common/report": {
            "post": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "埋点上报",
                "parameters": [
                    {
                        "description": "token和埋点数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ReportPayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "ok"
                    }
                }
            }
        },
        "/common/statics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取统计数据",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end_timestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"统计数据",
                        "schema": {
                            "$ref": "#/definitions/entity.GetStaticsResp"
                        }
                    }
                }
            }
        },
        "/doc/create": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "新建文档",
                "parameters": [
                    {
                        "description": "空间ID、标题、封面、内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateDocPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"文档详情",
                        "schema": {
                            "$ref": "#/definitions/model.Doc"
                        }
                    }
                }
            }
        },
        "/doc/delete": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "删除文档",
                "parameters": [
                    {
                        "description": "文档ID列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.DeleteDocPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/doc/docs": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "搜索文档",
                "parameters": [
                    {
                        "type": "string",
                        "name": "author_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "space_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"文档列表",
                        "schema": {
                            "$ref": "#/definitions/entity.GetDocsResp"
                        }
                    }
                }
            }
        },
        "/doc/drafts": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取文档草稿",
                "parameters": [
                    {
                        "type": "string",
                        "name": "doc_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"草稿列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Draft"
                            }
                        }
                    }
                }
            }
        },
        "/doc/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取文档详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文档ID",
                        "name": "doc_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"文档详情",
                        "schema": {
                            "$ref": "#/definitions/entity.GetDocInfoResp"
                        }
                    }
                }
            }
        },
        "/doc/update": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "更新文档",
                "parameters": [
                    {
                        "description": "文档ID、空间ID、标题、封面、内容、摘要",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateDocPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"更新后的文档详情",
                        "schema": {
                            "$ref": "#/definitions/model.Doc"
                        }
                    }
                }
            }
        },
        "/doc/update_drafts": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "更新文档草稿",
                "parameters": [
                    {
                        "description": "文档ID和草稿内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateDraftPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"更新后的草稿详情",
                        "schema": {
                            "$ref": "#/definitions/model.Draft"
                        }
                    }
                }
            }
        },
        "/feed/comment": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "评论动态",
                "parameters": [
                    {
                        "description": "动态ID、评论内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CommentPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"评论详情",
                        "schema": {
                            "$ref": "#/definitions/entity.CommentResp"
                        }
                    }
                }
            }
        },
        "/feed/comment_delete": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "删除评论",
                "parameters": [
                    {
                        "description": "动态ID、主评论ID、子评论ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.DeleteCommentPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/feed/comment_list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取评论列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "feed_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"评论列表",
                        "schema": {
                            "$ref": "#/definitions/entity.GetCommentListResp"
                        }
                    }
                }
            }
        },
        "/feed/comment_update": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "更新评论",
                "parameters": [
                    {
                        "description": "动态ID、主评论ID、子评论ID、评论内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateCommentPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"更新后的评论详情",
                        "schema": {
                            "$ref": "#/definitions/entity.CommentInfo"
                        }
                    }
                }
            }
        },
        "/feed/info": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取动态详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "动态ID",
                        "name": "feed_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"动态详情",
                        "schema": {
                            "$ref": "#/definitions/entity.GetFeedInfoResp"
                        }
                    }
                }
            }
        },
        "/feed/like": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "点赞|取消点赞 动态",
                "parameters": [
                    {
                        "description": "动态ID、点赞或取消点赞",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.LikeFeedPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/feed/list": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "搜索动态",
                "parameters": [
                    {
                        "type": "string",
                        "name": "author_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"动态列表",
                        "schema": {
                            "$ref": "#/definitions/entity.GetFeedListResp"
                        }
                    }
                }
            }
        },
        "/feed/related_feeds": {
            "get": {
                "description": "使用但不校验登录态。",
                "produces": [
                    "application/json"
                ],
                "summary": "获取同一空间下相关动态列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "space_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"动态列表",
                        "schema": {
                            "$ref": "#/definitions/entity.GetRelatedFeedsResp"
                        }
                    }
                }
            }
        },
        "/feed/reply": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "回复评论",
                "parameters": [
                    {
                        "description": "动态ID、评论ID、目标用户ID、回复内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ReplyPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"回复评论详情",
                        "schema": {
                            "$ref": "#/definitions/entity.ReplyInfo"
                        }
                    }
                }
            }
        },
        "/space/create": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "新建空间",
                "parameters": [
                    {
                        "description": "名称和描述",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateSpacePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"空间详情",
                        "schema": {
                            "$ref": "#/definitions/model.Space"
                        }
                    }
                }
            }
        },
        "/space/delete": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "删除空间",
                "parameters": [
                    {
                        "description": "空间ID列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.DeleteSpacePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/space/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取空间详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "空间ID",
                        "name": "space_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"空间详情",
                        "schema": {
                            "$ref": "#/definitions/entity.GetSpaceInfoResp"
                        }
                    }
                }
            }
        },
        "/space/search": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "搜索空间",
                "parameters": [
                    {
                        "type": "string",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "owner_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"空间列表",
                        "schema": {
                            "$ref": "#/definitions/entity.GetSpacesResp"
                        }
                    }
                }
            }
        },
        "/space/update": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "更新空间",
                "parameters": [
                    {
                        "description": "空间ID、名称和描述",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateSpacePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"更新后的空间详情",
                        "schema": {
                            "$ref": "#/definitions/model.Space"
                        }
                    }
                }
            }
        },
        "/user/cancel_collect_feed": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "取消收藏动态",
                "parameters": [
                    {
                        "description": "动态ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RemoveFeedFromCollectionPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/cancel_collect_wallpaper": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "取消收藏壁纸",
                "parameters": [
                    {
                        "description": "壁纸数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RemoveWallpaperFromCollectionPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/collect_feed": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "收藏动态",
                "parameters": [
                    {
                        "description": "动态ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.AddFeedToCollectionPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/collect_wallpaper": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "收藏壁纸",
                "parameters": [
                    {
                        "description": "壁纸数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.AddWallpaperToCollectionPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/collected_feeds": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取收藏的动态列表",
                "responses": {
                    "200": {
                        "description": "ok\" \"收藏的动态列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.FeedInfo"
                            }
                        }
                    }
                }
            }
        },
        "/user/collected_wallpapers": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取收藏的壁纸列表",
                "responses": {
                    "200": {
                        "description": "ok\" \"收藏的壁纸列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.WallpaperItem"
                            }
                        }
                    }
                }
            }
        },
        "/user/follow_user": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "关注用户",
                "parameters": [
                    {
                        "description": "用户ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.FollowUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/followed_users": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取关注的用户列表",
                "responses": {
                    "200": {
                        "description": "ok\" \"关注的用户列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.UserItem"
                            }
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取本人用户信息",
                "responses": {
                    "200": {
                        "description": "ok\" \"本人用户信息",
                        "schema": {
                            "$ref": "#/definitions/entity.Profile"
                        }
                    }
                }
            },
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "更新本人用户信息",
                "parameters": [
                    {
                        "description": "昵称和头像",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateProfilePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"更新后的本人用户信息",
                        "schema": {
                            "$ref": "#/definitions/entity.Profile"
                        }
                    }
                }
            }
        },
        "/user/sign_in": {
            "post": {
                "description": "微信授权登录｜Github授权登录",
                "produces": [
                    "application/json"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.LoginPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"Token和用户信息",
                        "schema": {
                            "$ref": "#/definitions/entity.LoginRes"
                        }
                    }
                }
            }
        },
        "/user/unfollow_user": {
            "post": {
                "description": "校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "取关用户",
                "parameters": [
                    {
                        "description": "用户ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UnfollowUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/user_info": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取其他人用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"用户信息",
                        "schema": {
                            "$ref": "#/definitions/entity.UserItem"
                        }
                    }
                }
            }
        },
        "/user/yd_callback": {
            "post": {
                "description": "提供给易登侧调用，获取用户扫码状态",
                "produces": [
                    "application/json"
                ],
                "summary": "易登回调",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.YDCallbackPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/user/yd_login_status": {
            "get": {
                "description": "用于微信扫码登录",
                "produces": [
                    "application/json"
                ],
                "summary": "检查易登状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "易登临时ID",
                        "name": "temp_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"是否成功登录",
                        "schema": {
                            "$ref": "#/definitions/entity.GetYDLoginStatusResp"
                        }
                    }
                }
            }
        },
        "/user/yd_qrcode": {
            "get": {
                "description": "用于微信扫码登录",
                "produces": [
                    "application/json"
                ],
                "summary": "获取易登二维码",
                "responses": {
                    "200": {
                        "description": "ok\" \"二维码链接和易登临时ID",
                        "schema": {
                            "$ref": "#/definitions/entity.GetYDQRCodeResp"
                        }
                    }
                }
            }
        },
        "/wallpaper/info": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "获取壁纸详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "壁纸链接",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"壁纸详情",
                        "schema": {
                            "$ref": "#/definitions/entity.GetWallpaperInfoResp"
                        }
                    }
                }
            }
        },
        "/wallpaper/search": {
            "get": {
                "description": "使用但不校验登录态",
                "produces": [
                    "application/json"
                ],
                "summary": "搜索壁纸",
                "parameters": [
                    {
                        "type": "string",
                        "name": "ai_art_filter",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "atleast",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "categories",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "colors",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "purity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "ratios",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "resolutions",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sorting",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "topRange",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"壁纸列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.WallpaperItem"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.AddFeedToCollectionPayload": {
            "type": "object",
            "required": [
                "feed_id"
            ],
            "properties": {
                "feed_id": {
                    "type": "string"
                }
            }
        },
        "entity.AddWallpaperToCollectionPayload": {
            "type": "object",
            "required": [
                "wallpaper"
            ],
            "properties": {
                "wallpaper": {
                    "$ref": "#/definitions/model.Wallpaper"
                }
            }
        },
        "entity.Author": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "entity.CommentInfo": {
            "type": "object",
            "properties": {
                "commentator": {
                    "$ref": "#/definitions/entity.Commentator"
                },
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sub_comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReplyInfo"
                    }
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.CommentPayload": {
            "type": "object",
            "required": [
                "content",
                "feed_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                }
            }
        },
        "entity.CommentResp": {
            "type": "object",
            "properties": {
                "commentator": {
                    "$ref": "#/definitions/entity.Commentator"
                },
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sub_comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ReplyInfo"
                    }
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.Commentator": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "entity.CreateDocPayload": {
            "type": "object",
            "required": [
                "space_id",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "entity.CreateSpacePayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.Creator": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "entity.DeleteCommentPayload": {
            "type": "object",
            "required": [
                "feed_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "sub_comment_id": {
                    "type": "string"
                }
            }
        },
        "entity.DeleteDocPayload": {
            "type": "object",
            "required": [
                "doc_ids"
            ],
            "properties": {
                "doc_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "entity.DeleteSpacePayload": {
            "type": "object",
            "required": [
                "space_ids"
            ],
            "properties": {
                "space_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "entity.DocInfo": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/entity.Author"
                },
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "public": {
                    "type": "boolean"
                },
                "space_id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "entity.FeedInfo": {
            "type": "object",
            "properties": {
                "collected": {
                    "type": "boolean"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Comment"
                    }
                },
                "comments_count": {
                    "type": "integer"
                },
                "creation_time": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/entity.Creator"
                },
                "creator_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.LikeInfo"
                    }
                },
                "likes_count": {
                    "type": "integer"
                },
                "subject": {
                    "$ref": "#/definitions/entity.DocInfo"
                },
                "subject_id": {
                    "type": "string"
                },
                "subject_type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "entity.FollowUserPayload": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.GetBucketTokenResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "entity.GetCommentListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CommentInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.GetDocInfoResp": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/entity.Author"
                },
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "public": {
                    "type": "boolean"
                },
                "space_id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "entity.GetDocsResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DocInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.GetFeedInfoResp": {
            "type": "object",
            "properties": {
                "collected": {
                    "type": "boolean"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Comment"
                    }
                },
                "comments_count": {
                    "type": "integer"
                },
                "creation_time": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/entity.Creator"
                },
                "creator_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.LikeInfo"
                    }
                },
                "likes_count": {
                    "type": "integer"
                },
                "subject": {
                    "$ref": "#/definitions/entity.DocInfo"
                },
                "subject_id": {
                    "type": "string"
                },
                "subject_type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "entity.GetFeedListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FeedInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.GetRelatedFeedsResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FeedInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.GetSignedURLResp": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "entity.GetSpaceInfoResp": {
            "type": "object",
            "properties": {
                "creation_time": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "entity.GetSpacesResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Space"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.GetStaticsResp": {
            "type": "object",
            "properties": {
                "pv": {
                    "type": "integer"
                },
                "uv": {
                    "type": "integer"
                }
            }
        },
        "entity.GetWallpaperInfoResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entity.WallpaperItem"
                }
            }
        },
        "entity.GetYDLoginStatusResp": {
            "type": "object",
            "properties": {
                "has_login": {
                    "type": "boolean"
                }
            }
        },
        "entity.GetYDQRCodeResp": {
            "type": "object",
            "properties": {
                "qrcode_url": {
                    "type": "string"
                },
                "temp_user_id": {
                    "type": "string"
                }
            }
        },
        "entity.LikeFeedPayload": {
            "type": "object",
            "required": [
                "event",
                "feed_id"
            ],
            "properties": {
                "event": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                }
            }
        },
        "entity.LikeInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.LoginPayload": {
            "type": "object",
            "required": [
                "code",
                "type"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "entity.LoginRes": {
            "type": "object",
            "properties": {
                "associated": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "collected_feed_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "collected_wallpapers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Wallpaper"
                    }
                },
                "creation_time": {
                    "type": "string"
                },
                "followed_user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "github_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "wechat_id": {
                    "type": "string"
                }
            }
        },
        "entity.Profile": {
            "type": "object",
            "properties": {
                "associated": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "github_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "wechat_id": {
                    "type": "string"
                }
            }
        },
        "entity.RemoveFeedFromCollectionPayload": {
            "type": "object",
            "required": [
                "feed_id"
            ],
            "properties": {
                "feed_id": {
                    "type": "string"
                }
            }
        },
        "entity.RemoveWallpaperFromCollectionPayload": {
            "type": "object",
            "required": [
                "wallpaper_id"
            ],
            "properties": {
                "wallpaper_id": {
                    "type": "string"
                }
            }
        },
        "entity.ReplyInfo": {
            "type": "object",
            "properties": {
                "commentator": {
                    "$ref": "#/definitions/entity.Commentator"
                },
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reply_commentator": {
                    "$ref": "#/definitions/entity.Commentator"
                },
                "reply_user_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.ReplyPayload": {
            "type": "object",
            "required": [
                "content",
                "feed_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "reply_user_id": {
                    "type": "string"
                }
            }
        },
        "entity.ReportPayload": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {}
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "entity.UnfollowUserPayload": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateCommentPayload": {
            "type": "object",
            "required": [
                "feed_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "sub_comment_id": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateDocPayload": {
            "type": "object",
            "required": [
                "doc_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "public": {
                    "type": "boolean"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateDraftPayload": {
            "type": "object",
            "required": [
                "content",
                "doc_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateProfilePayload": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateSpacePayload": {
            "type": "object",
            "required": [
                "space_id"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "entity.UserItem": {
            "type": "object",
            "properties": {
                "associated": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "collected": {
                    "type": "boolean"
                },
                "creation_time": {
                    "type": "string"
                },
                "github_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "wechat_id": {
                    "type": "string"
                }
            }
        },
        "entity.WallpaperItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "collected": {
                    "type": "boolean"
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "dimension_x": {
                    "type": "integer"
                },
                "dimension_y": {
                    "type": "integer"
                },
                "favorites": {
                    "type": "integer"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "purity": {
                    "type": "string"
                },
                "ratio": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                },
                "short_url": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                },
                "thumbs": {
                    "$ref": "#/definitions/model.Thumbs"
                },
                "url": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "entity.WeChatUserInfo": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "openId": {
                    "type": "string"
                }
            }
        },
        "entity.YDCallbackPayload": {
            "type": "object",
            "required": [
                "tempUserId"
            ],
            "properties": {
                "cancelLogin": {
                    "type": "boolean"
                },
                "scanSuccess": {
                    "type": "boolean"
                },
                "tempUserId": {
                    "type": "string"
                },
                "wxMaUserInfo": {
                    "$ref": "#/definitions/entity.WeChatUserInfo"
                }
            }
        },
        "model.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sub_comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubComment"
                    }
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Doc": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "doc_id": {
                    "type": "string"
                },
                "public": {
                    "type": "boolean"
                },
                "space_id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "model.Draft": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                }
            }
        },
        "model.Like": {
            "type": "object",
            "properties": {
                "creation_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Space": {
            "type": "object",
            "properties": {
                "creation_time": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "model.SubComment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "creation_time": {
                    "type": "string"
                },
                "feed_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reply_user_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Tag": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "purity": {
                    "type": "string"
                }
            }
        },
        "model.Thumbs": {
            "type": "object",
            "properties": {
                "large": {
                    "type": "string"
                },
                "original": {
                    "type": "string"
                },
                "small": {
                    "type": "string"
                }
            }
        },
        "model.Wallpaper": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "dimension_x": {
                    "type": "integer"
                },
                "dimension_y": {
                    "type": "integer"
                },
                "favorites": {
                    "type": "integer"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "purity": {
                    "type": "string"
                },
                "ratio": {
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                },
                "short_url": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                },
                "thumbs": {
                    "$ref": "#/definitions/model.Thumbs"
                },
                "url": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
